# config.yaml
server:
  address: ":8080"
  readTimeout: 5s
  writeTimeout: 10s

redis:
  address: "localhost:6379"
  password: ""
  db: 0

rateLimit:
  keyPrefix: "ratelimit"
  capacity: 10.0  
  tokensPerSecond: 0.1  # 초당 충전되는 토큰
  tokens: 1.0
  type: "tokenbucket"